@startuml

title __DATABASE's Class Diagram__\n

  namespace com.example.society {
    namespace database {
      class com.example.society.database.DBinformation {
          {static} + DATABASE_LOGINTABLE : String
          {static} + DATABASE_NAME : String
          {static} + DATABASE_ORDERTABLE : String
          {static} + DATABASE_VERION : int
          {static} + ORDER_CONTENT : String
          {static} + ORDER_ID : String
          {static} + ORDER_TIME : String
          {static} + USERS_AGE : String
          {static} + USERS_CITY : String
          {static} + USERS_GENDER : String
          {static} + USERS_ID : String
          {static} + USERS_NAME : String
          {static} + USERS_NUM : String
          {static} + USERS_PWD : String
          {static} + USERS_STYLE : String
          {static} + getTime()
      }
    }
  }
  

  namespace com.example.society {
    namespace database {
      class com.example.society.database.MD5Utils {
          {static} + md5Password()
      }
    }
  }
  

  namespace com.example.society {
    namespace database {
      class com.example.society.database.SQLiteHelper {
          {static} - sqLiteDatabase : SQLiteDatabase
          + SQLiteHelper()
          + onCreate()
          + onUpgrade()
      }
    }
  }
  

  namespace com.example.society {
    namespace database {
      class com.example.society.database.SQLiteHelper.Eassy {
          + Eassy()
          + deleteData()
          + insertData()
          + query()
          + updateData()
      }
    }
  }
  

  namespace com.example.society {
    namespace database {
      class com.example.society.database.SQLiteHelper.User {
          + User()
          + deleteData()
          + insertData()
          + query()
          + updateData()
          + updatemesData()
          + userquery()
      }
    }
  }
  

  com.example.society.database.SQLiteHelper -up-|> android.database.sqlite.SQLiteOpenHelper
  com.example.society.database.SQLiteHelper +-down- com.example.society.database.SQLiteHelper.Eassy
  com.example.society.database.SQLiteHelper +-down- com.example.society.database.SQLiteHelper.User


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
