@startuml

title __BEAN's Class Diagram__\n

  namespace com.example.society {
    namespace Bean {
      class com.example.society.Bean.CourseBean {
          + icon : String
          + id : int
          + imgTitle : String
          + intro : String
          + title : String
      }
    }
  }
  

  namespace com.example.society {
    namespace Bean {
      class com.example.society.Bean.ExercisesBean {
          + a : String
          + answer : int
          + b : String
          + background : int
          + c : String
          + content : String
          + d : String
          + id : int
          + select : int
          + subject : String
          + subjectId : int
          + title : String
      }
    }
  }
  

  namespace com.example.society {
    namespace Bean {
      class com.example.society.Bean.Loginuser {
          - age : String
          - city : String
          - gender : String
          - id : String
          - name : String
          - num : String
          - pwd : String
          - style : String
          + getAge()
          + getCity()
          + getGender()
          + getId()
          + getName()
          + getNum()
          + getPwd()
          + getStyle()
          + setAge()
          + setCity()
          + setGender()
          + setId()
          + setName()
          + setNum()
          + setPwd()
          + setStyle()
          + toString()
      }
    }
  }
  

  namespace com.example.society {
    namespace Bean {
      class com.example.society.Bean.OrderBean {
          - content : String
          - id : String
          - time : String
          + getContent()
          + getId()
          + getTime()
          + setContent()
          + setId()
          + setTime()
          + toString()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
